### ISSUE TITLE
Suggestion: trunk support?

### ISSUE THREAD

**Issue by Vanquish081** [Achimobil/FS22_aPalletAutoLoader#9]
Don't plan on adding log support?

**Comment by Achimobil** [comment]
Perhaps. but currently I think not. Reason: It is made for pallets and then extended to also use bales, because both can be used on flat plate. for wood logs you need a closed thing. But when you can see in #5 . There this is the topic as wish noted to built in and I already have the confirmation of Loki to use his log implementation, when I decide to build it in.
